In [15]:
### Carregar as Libraries
import numpy as np
import pandas as pd

### Importing Dataset
dataset = pd.read_csv('CNN_features_extracted_MAX.csv',encoding='utf-8')

# Obtendo os nomes das colunas Numéricas
tipos_numericos = ['int32', 'int64', 'float16', 'float32', 'float64']
cols_num = dataset.select_dtypes(include=tipos_numericos)

## Selecionando os atributos numéricos
colunas_numericas = list(cols_num.columns)

## Pegar a classe
coluna_classe = dataset['classe']

## Separando os atributos da classe
X = dataset[colunas_numericas] # Features
y = dataset.classe             # Target variable (classe)

In [13]:
def train_and_evaluate(X, y, test_sizes, random_state=1):
    
    for test_size in test_sizes:
        # Separando dataset em duas partes: treinamento e teste
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)

        # Criar um objeto Gaussian Classifier
        gnb = GaussianNB(priors=None, var_smoothing=1e-9)

        # Treinar o classificador
        gnb.fit(X_train, y_train)

        # Prever a resposta para o conjunto de dados de teste
        y_pred = gnb.predict(X_test)

        # Acurácia do Modelo
        acuracia = metrics.accuracy_score(y_test, y_pred)
        print(f'test_size={test_size}: Accuracy: {acuracia:.3f}')
        print()

        # Matriz de confusão
        print(f'Matriz de confusão para test_size={test_size}:')
        print(confusion_matrix(y_test, y_pred))
        print()



In [16]:
# Lista de tamanhos de teste para avaliar
test_sizes = [0.3, 0.2, 0.1]

# Chame a função com seus dados e os tamanhos de teste desejados
train_and_evaluate(X, y, test_sizes)

test_size=0.3: Accuracy: 0.496

Matriz de confusão para test_size=0.3:
[[ 10 119]
 [  2 109]]

test_size=0.2: Accuracy: 0.519

Matriz de confusão para test_size=0.2:
[[ 8 74]
 [ 3 75]]

test_size=0.1: Accuracy: 0.500

Matriz de confusão para test_size=0.1:
[[ 5 38]
 [ 2 35]]

